[package]
name = "falcon_sql_frontend"
version.workspace = true
edition.workspace = true

[dependencies]
falcon_common = { path = "../falcon_common" }
sqlparser.workspace = true
tracing.workspace = true
